# Generated by Django 4.1.4 on 2022-12-15 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='nip',
        ),
    ]
