# Generated by Django 4.1.4 on 2022-12-15 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_rename_phone_user_nip'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=100),
        ),
    ]
