# Generated by Django 4.1.4 on 2023-03-06 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_alter_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='points',
        ),
    ]
