# Generated by Django 4.1.4 on 2022-12-16 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_user_points'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Employers'},
        ),
    ]
