# Generated by Django 4.1.4 on 2022-12-16 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_alter_user_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='points',
            new_name='tokens',
        ),
    ]
