# Generated by Django 4.1.4 on 2022-12-16 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_rename_points_user_tokens'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='tokens',
            new_name='points',
        ),
    ]
