# Generated by Django 4.1.7 on 2023-03-22 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='company_name',
        ),
    ]
