# Generated by Django 4.1.7 on 2023-03-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0006_rename_name_user_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nip',
            field=models.CharField(max_length=255),
        ),
    ]
