# Generated by Django 4.1.7 on 2023-04-13 23:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0007_alter_user_nip'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='form',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
    ]
