# Generated by Django 4.1.7 on 2023-04-14 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0008_user_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='form',
        ),
    ]
