# Generated by Django 4.1.7 on 2023-04-14 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0009_remove_user_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='form',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
