# Generated by Django 4.1.7 on 2023-06-12 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0011_user_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='points',
        ),
    ]
