# Generated by Django 4.1.7 on 2023-07-01 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0013_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
