# Generated by Django 4.1.7 on 2023-07-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0014_remove_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tokens',
            field=models.IntegerField(default=0),
        ),
    ]
