# Generated by Django 4.1.7 on 2023-07-06 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0015_user_tokens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tokens',
        ),
    ]
