# Generated by Django 4.1.7 on 2023-07-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0016_remove_user_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tokens',
            field=models.IntegerField(default=3),
        ),
    ]
