# Generated by Django 4.1.4 on 2023-02-11 09:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Question Categories',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(to='Survey.questioncategories')),
            ],
            options={
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='GeneratedCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Candidates.candidates')),
            ],
            options={
                'verbose_name_plural': 'Generated codes',
            },
        ),
        migrations.CreateModel(
            name='CandidateAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.PositiveSmallIntegerField(choices=[(1, 'Zdecydowanie nie'), (2, 'Raczej nie'), (3, 'Nie mam zdania'), (5, 'Raczej tak'), (6, 'Zdecydowanie tak')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Candidates.candidates')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidateanswers_question', to='Survey.questions')),
            ],
            options={
                'verbose_name_plural': 'Candidate answers',
                'unique_together': {('question', 'candidate')},
            },
        ),
        migrations.CreateModel(
            name='AbilityQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reverse_values', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilityquestions_ability', to='Candidates.abilities')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilityquestions_question', to='Survey.questions')),
            ],
            options={
                'verbose_name_plural': 'Ability questions',
                'unique_together': {('question', 'ability')},
            },
        ),
    ]
