# Generated by Django 4.1.4 on 2023-02-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='category',
            field=models.CharField(choices=[('all', 'all'), ('sales', 'sales'), ('administration', 'administration'), ('customer_service', 'customer_service')], max_length=30),
        ),
    ]
