# Generated by Django 4.1.4 on 2023-02-15 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0005_rename_experience_administration_candidates_experience_office_administration'),
        ('Survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateanswers',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidateanswers_candidate', to='Candidates.candidates'),
        ),
    ]
