# Generated by Django 4.1.4 on 2023-02-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0002_alter_candidateanswers_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedcodes',
            name='code',
            field=models.UUIDField(default='cca727'),
        ),
    ]
