# Generated by Django 4.1.4 on 2023-02-04 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0002_alter_questions_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='type',
            field=models.CharField(choices=[('SELECT', 'Select from multiple choices'), ('TEXT', 'Enter text'), ('MULTI', 'Select multiple choices')], default='SELECT', max_length=30),
        ),
        migrations.AlterField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='Survey.questions'),
        ),
    ]
