# Generated by Django 4.1.4 on 2023-02-15 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0005_rename_experience_administration_candidates_experience_office_administration'),
        ('Survey', '0003_alter_generatedcodes_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedcodes',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_code', to='Candidates.candidates'),
        ),
        migrations.AlterField(
            model_name='generatedcodes',
            name='code',
            field=models.UUIDField(default='cea9c3'),
        ),
    ]
