# Generated by Django 4.1.4 on 2023-02-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0003_questions_type_alter_answers_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='type',
        ),
        migrations.AlterField(
            model_name='questions',
            name='category',
            field=models.CharField(choices=[('all', 'all'), ('sales', 'sales'), ('administration', 'administration'), ('customer_service', 'customer_service')], default='all', max_length=30),
        ),
    ]
