# Generated by Django 4.1.4 on 2023-02-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0004_remove_questions_type_alter_questions_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswers',
            name='text',
        ),
        migrations.AddField(
            model_name='useranswers',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='useranswers',
            name='answer',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Zdecydowanie nie'), (2, 'Raczej nie'), (3, 'Nie mam zdania'), (5, 'Raczej tak'), (6, 'Zdecydowanie tak')]),
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
    ]
