# Generated by Django 4.1.4 on 2023-02-17 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0005_alter_generatedcodes_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='category',
            field=models.ManyToManyField(related_name='questions_category', to='Survey.questioncategories'),
        ),
    ]
