# Generated by Django 4.1.4 on 2023-02-06 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0007_alter_candidates_education_and_more'),
        ('Survey', '0005_remove_useranswers_text_useranswers_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.PositiveSmallIntegerField(choices=[(1, 'Zdecydowanie nie'), (2, 'Raczej nie'), (3, 'Nie mam zdania'), (5, 'Raczej tak'), (6, 'Zdecydowanie tak')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Candidates.candidates')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidateanswers_question', to='Survey.questions')),
            ],
            options={
                'verbose_name_plural': 'Candidate answers',
            },
        ),
        migrations.DeleteModel(
            name='UserAnswers',
        ),
    ]
