# Generated by Django 4.1.4 on 2023-03-06 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0008_candidates_province'),
        ('Survey', '0006_alter_questions_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedcodes',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_code', to='Candidates.candidates', unique=True),
        ),
    ]
