# Generated by Django 4.1.4 on 2023-02-07 00:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0007_alter_candidates_education_and_more'),
        ('Survey', '0006_candidateanswers_delete_useranswers'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Candidates.candidates')),
            ],
            options={
                'verbose_name_plural': 'Generated codes',
            },
        ),
        migrations.CreateModel(
            name='AbilityQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilityquestions_ability', to='Candidates.abilities')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilityquestions_question', to='Survey.questions')),
            ],
            options={
                'verbose_name_plural': 'Ability questions',
            },
        ),
    ]
