# Generated by Django 4.1.4 on 2023-03-07 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0009_delete_professions_candidates_profession_and_more'),
        ('Survey', '0007_alter_generatedcodes_candidate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionCategories',
            new_name='Categories',
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='generatedcodes',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_code', to='Candidates.candidates'),
        ),
    ]
