# Generated by Django 4.1.7 on 2023-03-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0008_rename_questioncategories_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedcodes',
            name='candidate',
        ),
        migrations.AddField(
            model_name='generatedcodes',
            name='phone',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
    ]
