# Generated by Django 4.1.4 on 2023-02-07 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0009_abilityquestions_reverse_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Question Categories',
            },
        ),
        migrations.RemoveField(
            model_name='questions',
            name='category',
        ),
        migrations.AddField(
            model_name='questions',
            name='category',
            field=models.ManyToManyField(to='Survey.questioncategories'),
        ),
    ]
