# Generated by Django 4.1.4 on 2023-02-07 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0007_alter_candidates_education_and_more'),
        ('Survey', '0010_questioncategories_remove_questions_category_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candidateanswers',
            unique_together={('question', 'candidate')},
        ),
    ]
