# Generated by Django 4.1.7 on 2023-04-23 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Points', '0005_orders_extorderid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='extOrderId',
            new_name='order_id',
        ),
    ]
