# Generated by Django 4.1.7 on 2023-07-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Points', '0007_alter_orders_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='expiration_date',
            field=models.DateTimeField(default='2023-07-16 10:53:43.09966+00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='remaining_tokens',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='tokens',
            field=models.IntegerField(),
        ),
    ]
