# Generated by Django 4.1.4 on 2023-02-11 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Abilities',
            },
        ),
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.CharField(max_length=255, unique=True)),
                ('salary_expectation', models.CharField(choices=[('mniej niż 2999 zł', 'mniej niż 2999 zł'), ('od 3000 zł do 3499 zł', 'od 3000 zł do 3499 zł'), ('od 3500 zł do 3999 zł', 'od 3500 zł do 3999 zł'), ('od 4000 zł do 4499 zł', 'od 4000 zł do 4499 zł'), ('od 4500 zł do 4999 zł', 'od 4500 zł do 4999 zł'), ('od 5000 zł do 5999 zł', 'od 5000 zł do 5999 zł'), ('powyżej 6000 zł', 'powyżej 6000 zł')], max_length=100)),
                ('availability', models.CharField(max_length=255)),
                ('job_position', models.CharField(max_length=100)),
                ('experience_sales', models.IntegerField(default=0)),
                ('experience_customer_service', models.IntegerField(default=0)),
                ('experience_administration', models.IntegerField(default=0)),
                ('education', models.CharField(choices=[('wykształcenie podstawowe (posiadają osoby, które ukończyły szkołę podstawową)', 'wykształcenie podstawowe (posiadają osoby, które ukończyły szkołę podstawową)'), ('wykształcenie średnie (posiadają osoby, które ukończyły liceum lub pokrewne)', 'wykształcenie średnie (posiadają osoby, które ukończyły liceum lub pokrewne)'), ('wykształcenie wyższe (posiadają osoby, które na studiach wyższych (I, II lub III stopnia) uzyskały tytuł zawodowy licencjata, inżyniera, magistra lub magistra inżyniera, lub uzyskały stopień naukowy doktora)', 'wykształcenie wyższe (posiadają osoby, które na studiach wyższych (I, II lub III stopnia) uzyskały tytuł zawodowy licencjata, inżyniera, magistra lub magistra inżyniera, lub uzyskały stopień naukowy doktora)')], max_length=255)),
                ('driving_license', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Candidates',
            },
        ),
        migrations.CreateModel(
            name='PurchasedOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchasedoffers_candidate', to='Candidates.candidates')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchasedoffers_employer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Purchased offers',
                'unique_together': {('employer', 'candidate')},
            },
        ),
        migrations.CreateModel(
            name='CandidateAbilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=0, max_digits=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidateabilities_ability', to='Candidates.abilities')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidateabilities_candidate', to='Candidates.candidates')),
            ],
            options={
                'verbose_name_plural': 'Candidate abilities',
                'unique_together': {('candidate', 'ability')},
            },
        ),
    ]
