# Generated by Django 4.1.4 on 2023-02-14 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
