# Generated by Django 4.1.4 on 2022-12-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='candidates',
            index=models.Index(fields=['is_verified'], name='Candidates__is_veri_fde4a5_idx'),
        ),
    ]
