# Generated by Django 4.1.4 on 2023-02-11 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Professions',
            },
        ),
        migrations.CreateModel(
            name='CandidateProfessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidateprofessions_candidate', to='Candidates.candidates')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidateprofessions_ability', to='Candidates.professions')),
            ],
            options={
                'verbose_name_plural': 'Candidate professions',
                'unique_together': {('candidate', 'profession')},
            },
        ),
    ]
