# Generated by Django 4.1.4 on 2022-12-15 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0002_abilities_candidates_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidates',
            old_name='phone',
            new_name='nip',
        ),
    ]
