# Generated by Django 4.1.4 on 2022-12-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0002_alter_candidates_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
