# Generated by Django 4.1.4 on 2023-02-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0002_professions_candidateprofessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='preferred_professions',
            field=models.ManyToManyField(through='Candidates.CandidateProfessions', to='Candidates.professions'),
        ),
    ]
