# Generated by Django 4.1.4 on 2022-12-21 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0002_candidates_candidates__is_veri_fde4a5_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='candidates',
            name='Candidates__is_veri_fde4a5_idx',
        ),
    ]
