# Generated by Django 4.1.4 on 2023-02-11 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0003_candidates_preferred_professions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidates',
            name='preferred_professions',
        ),
    ]
