# Generated by Django 4.1.4 on 2023-02-05 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0003_candidateabilities_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='salary',
        ),
        migrations.AddField(
            model_name='candidates',
            name='availability',
            field=models.CharField(default='pół etatu', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidates',
            name='driving_license',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidates',
            name='education',
            field=models.IntegerField(choices=[(1, 'Wykształcenie podstawowe'), (2, 'Wykształcenie średnie'), (3, 'Wykształcenie wyższe')], default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidates',
            name='experience_administration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidates',
            name='experience_customer_service',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidates',
            name='experience_sales',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidates',
            name='job_position',
            field=models.CharField(default='manager', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidates',
            name='salary_expectation',
            field=models.IntegerField(choices=[(1, 'mniej niż 2999 zł'), (2, 'od 3000 zł do 3499 zł'), (3, 'od 3500 zł do 3999 zł'), (4, 'od 4000 zł do 4499 zł'), (5, 'od 4500 zł do 4999 zł'), (6, 'od 5000 zł do 5999 zł'), (7, 'powyżej 6000 zł')], default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidates',
            name='preferred_professions',
            field=models.ManyToManyField(to='Candidates.professions'),
        ),
    ]
