# Generated by Django 4.1.4 on 2022-12-15 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0003_rename_phone_candidates_nip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidates',
            old_name='nip',
            new_name='phone',
        ),
    ]
