# Generated by Django 4.1.4 on 2023-02-15 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0004_alter_candidates_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidates',
            old_name='experience_administration',
            new_name='experience_office_administration',
        ),
    ]
