# Generated by Django 4.1.4 on 2022-12-16 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Candidates', '0004_rename_nip_candidates_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidateabilities',
            options={'verbose_name_plural': 'Candidate abilities'},
        ),
        migrations.AddField(
            model_name='candidates',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=0, default=5, max_digits=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidateabilities',
            name='ability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidateabilities_abilitie', to='Candidates.abilities'),
        ),
        migrations.AlterField(
            model_name='candidateabilities',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidateabilities_candidate', to='Candidates.candidates'),
        ),
        migrations.CreateModel(
            name='PurchasedOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchasedoffers_candidate', to='Candidates.candidates')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchasedoffers_employer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Purchased offers',
                'unique_together': {('employer', 'candidate')},
            },
        ),
    ]
