# Generated by Django 4.1.4 on 2023-02-11 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0004_remove_candidates_preferred_professions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofessions',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidateprofessions_candidate', to='Candidates.candidates'),
        ),
        migrations.AlterField(
            model_name='candidateprofessions',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidateprofessions_profession', to='Candidates.professions'),
        ),
    ]
