# Generated by Django 4.1.4 on 2023-02-06 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0005_alter_candidates_education_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professions',
            options={'verbose_name_plural': 'Professions'},
        ),
    ]
