# Generated by Django 4.1.4 on 2022-12-16 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0005_alter_candidateabilities_options_candidates_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateabilities',
            name='ability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidateabilities_ability', to='Candidates.abilities'),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=100, null=True),
        ),
    ]
