# Generated by Django 4.1.4 on 2023-02-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0005_alter_candidateprofessions_candidate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='preferred_professions',
            field=models.ManyToManyField(through='Candidates.CandidateProfessions', to='Candidates.professions'),
        ),
    ]
