# Generated by Django 4.1.4 on 2023-02-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0005_rename_experience_administration_candidates_experience_office_administration'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='abilities',
            field=models.ManyToManyField(through='Candidates.CandidateAbilities', to='Candidates.abilities'),
        ),
    ]
