# Generated by Django 4.1.4 on 2023-02-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0006_candidates_abilities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidates',
            name='preferred_professions',
        ),
        migrations.AddField(
            model_name='candidates',
            name='birth_date',
            field=models.DateField(default='2000-07-21'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidates',
            name='preferred_profession',
            field=models.CharField(choices=[('Sprzedaż', 'Sprzedaż'), ('Administracja biurowa', 'Administracja biurowa'), ('Obsługa klienta', 'Obsługa klienta')], default='Sprzedaż', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CandidateProfessions',
        ),
    ]
