# Generated by Django 4.1.4 on 2023-02-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0007_alter_candidates_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateabilities',
            name='percentage',
            field=models.DecimalField(decimal_places=0, max_digits=3, null=True),
        ),
    ]
