# Generated by Django 4.1.4 on 2023-02-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0008_alter_candidateabilities_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='education',
            field=models.CharField(choices=[('wykształcenie podstawowe (posiadają osoby, które ukończyły szkołę podstawową)', 'wykształcenie podstawowe (posiadają osoby, które ukończyły szkołę podstawową)'), ('wykształcenie średnie (posiadają osoby, które ukończyły liceum lub pokrewne)', 'wykształcenie średnie (posiadają osoby, które ukończyły liceum lub pokrewne)'), ('wykształcenie wyższe (posiadają osoby, które na studiach wyższych (I, II lub III stopnia)', 'wykształcenie wyższe (posiadają osoby, które na studiach wyższych (I, II lub III stopnia)')], max_length=255),
        ),
    ]
