# Generated by Django 4.1.4 on 2023-03-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0008_candidates_province'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Professions',
        ),
        migrations.AddField(
            model_name='candidates',
            name='profession',
            field=models.CharField(choices=[('Sales', 'Sales'), ('Office administration', 'Office administration'), ('Customer service', 'Customer service')], default='Sales', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidates',
            name='preferred_profession',
            field=models.CharField(choices=[('Sales', 'Sales'), ('Office administration', 'Office administration'), ('Customer service', 'Customer service')], max_length=100),
        ),
    ]
