# Generated by Django 4.1.4 on 2023-03-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0009_delete_professions_candidates_profession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='preferred_profession',
            field=models.CharField(choices=[('sales', 'sales'), ('office_administration', 'office_administration'), ('customer_service', 'customer_service')], max_length=100),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='profession',
            field=models.CharField(choices=[('sales', 'sales'), ('office_administration', 'office_administration'), ('customer_service', 'customer_service')], max_length=100),
        ),
    ]
