# Generated by Django 4.1.4 on 2023-03-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0011_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='message',
            field=models.CharField(default='tet', max_length=255),
            preserve_default=False,
        ),
    ]
