# Generated by Django 4.1.4 on 2023-03-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0012_reports_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='has_job',
            field=models.BooleanField(default=False),
        ),
    ]
