# Generated by Django 4.1.7 on 2023-03-22 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0013_candidates_has_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidates',
            name='preferred_profession',
        ),
    ]
