# Generated by Django 4.1.7 on 2023-05-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0014_remove_candidates_preferred_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='salary_expectation',
            field=models.CharField(choices=[('poniżej 3500 zł', 'poniżej 3500 zł'), ('od 3501 do 4500 zł', 'od 3501 do 4500 zł'), ('od 4501 do 5500 zł', 'od 4501 do 5500 zł'), ('od 5501 do 6500 zł', 'od 5501 do 6500 zł'), ('od 6500 do 10000 zł', 'od 6500 do 10000 zł'), ('powyżej 10001 zł', 'powyżej 10001 zł')], max_length=100),
        ),
    ]
