# Generated by Django 4.1.7 on 2023-05-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0015_alter_candidates_salary_expectation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='education',
            field=models.CharField(choices=[('wykształcenie średnie (posiadają osoby, które ukończyły liceum lub pokrewne)', 'wykształcenie średnie (posiadają osoby, które ukończyły liceum lub pokrewne)'), ('wykształcenie wyższe (posiadają osoby, które uzyskały tytuł zawodowy licencjata, inżyniera, magistra lub magistra inżyniera, lub uzyskały stopień naukowy doktora)', 'wykształcenie wyższe (posiadają osoby, które uzyskały tytuł zawodowy licencjata, inżyniera, magistra lub magistra inżyniera, lub uzyskały stopień naukowy doktora)')], max_length=255),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='salary_expectation',
            field=models.CharField(choices=[('poniżej 3500 zł', 'poniżej 3500 zł'), ('od 3500 do 4500 zł', 'od 3500 do 4500 zł'), ('od 4501 do 5500 zł', 'od 4501 do 5500 zł'), ('od 5501 do 6500 zł', 'od 5501 do 6500 zł'), ('od 6501 do 10000 zł', 'od 6501 do 10000 zł'), ('powyżej 10000 zł', 'powyżej 10000 zł')], max_length=100),
        ),
    ]
