# Generated by Django 4.1.7 on 2023-06-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0016_alter_candidates_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedoffers',
            name='points',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
