# Generated by Django 4.1.7 on 2023-06-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0017_purchasedoffers_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='profession',
            field=models.CharField(choices=[('sales', 'sales'), ('office_administration', 'office_administration'), ('customer_service', 'customer_service')], max_length=100, null=True),
        ),
    ]
