# Generated by Django 4.1.7 on 2023-06-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0018_alter_candidates_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='completed_surveys',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
