# Generated by Django 4.1.7 on 2023-06-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0019_candidates_completed_surveys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
