# Generated by Django 4.1.7 on 2023-09-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0020_alter_candidates_is_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('profession', models.CharField(choices=[('sales', 'sales'), ('office_administration', 'office_administration'), ('customer_service', 'customer_service')], max_length=100, null=True)),
            ],
        ),
    ]
