# Generated by Django 4.1.7 on 2023-09-27 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0021_industries'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateIndustries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidateindustries_candidate', to='Candidates.candidates')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidateindustries_industry', to='Candidates.industries')),
            ],
        ),
    ]
