# Generated by Django 4.1.7 on 2023-09-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0022_candidateindustries'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='contract_type',
            field=models.CharField(choices=[('Umowa zlecenie / Umowa o dzieło)', 'Umowa zlecenie / Umowa o dzieło'), ('Umowa o pracę', 'Umowa o pracę'), ('Kontrakt B2B', 'Kontrakt B2B')], max_length=255, null=True),
        ),
    ]
