# Generated by Django 4.1.7 on 2023-09-29 11:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0023_candidates_contract_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='contract_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Umowa zlecenie / Umowa o dzieło)', 'Umowa zlecenie / Umowa o dzieło'), ('Umowa o pracę', 'Umowa o pracę'), ('Kontrakt B2B', 'Kontrakt B2B')], max_length=255), null=True, size=None),
        ),
    ]
