# Generated by Django 4.1.7 on 2023-09-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0024_alter_candidates_contract_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='location',
            field=models.JSONField(null=True),
        ),
    ]
