# Generated by Django 4.1.7 on 2023-09-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0026_alter_candidates_contract_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='location',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='province',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
