# Generated by Django 4.1.7 on 2023-10-10 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0027_alter_candidates_location_alter_candidates_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidates',
            name='province',
        ),
    ]
