# Generated by Django 4.1.7 on 2023-10-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0028_remove_candidates_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='province',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
