# Generated by Django 4.1.7 on 2023-10-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Codes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codes',
            name='type',
            field=models.CharField(default='reward', max_length=255),
            preserve_default=False,
        ),
    ]
