# Generated by Django 4.1.7 on 2023-10-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Codes', '0002_codes_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='codes',
            name='tokens',
            field=models.IntegerField(null=True),
        ),
    ]
