# Generated by Django 4.1.7 on 2023-10-10 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Codes', '0003_codes_tokens'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codes',
            old_name='tokens',
            new_name='price',
        ),
    ]
