# Generated by Django 4.1.7 on 2023-10-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Codes', '0004_rename_tokens_codes_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codes',
            name='price',
        ),
        migrations.AddField(
            model_name='usedcodes',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
